/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package admin.ui;

import Operations.Checks;
import javax.swing.JOptionPane;
import model.dao.BookTypeDAO;
import model.dao.LoginInfoDAO;
import model.to.BookTypeTO;
import model.to.LoginInfoTO;

/**
 *
 * @author DELL
 */
public class AddBookType extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddBookType
     */
    public AddBookType() {
        initComponents();
    }
 public AddBookType(BookTypeTO btto) {
        this();
        if(btto!=null){
            jtfTypeID.setText(btto.getTypeID());
            jtfTypeName.setText(btto.getTypeName());
            jtfTypeID.setEditable(false);
            btnBookType.setText("Update Book Type");
            setTitle("Update Book Type");
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtfTypeID = new javax.swing.JTextField();
        jtfTypeName = new javax.swing.JTextField();
        btnBookType = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setClosable(true);
        setIconifiable(true);
        setTitle("Add Book Type");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Enter Type ID");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Enter Type Name");

        btnBookType.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBookType.setText("Add Book Type");
        btnBookType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookTypeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(141, 141, 141)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfTypeName, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(jtfTypeID)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addComponent(btnBookType, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfTypeID, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(143, 143, 143)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfTypeName, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(btnBookType, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBookTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookTypeActionPerformed
         String TypeID=jtfTypeID.getText();
        String TypeName=jtfTypeName.getText();
       // String RoleName=jtfRoleName.getText();
        String message="";
        if(Checks.isEmpty(TypeID)||Checks.isEmpty(TypeName)){
            message="Please Fill All The Boxes";
        }else{
            BookTypeTO data=new BookTypeTO();
            data.setTypeID(TypeID);
            data.setTypeName(TypeName);
            BookTypeDAO action=new BookTypeDAO();
            if(btnBookType.getText().contains("Add")){
            if(action.insertRecord(data)){
                message="New Book type  Is added To The System";
            
            }else{
                message=action.getErrorMessage();
            }
            }else if(btnBookType.getText().contains("Update"));{
            if(action.updateRecord(data)){
                message="New Book type  Is updated To The System";
            } else{
                message=action.getErrorMessage();
            }
            ViewBookType atb= new ViewBookType();
            atb.setVisible(true);
            getDesktopPane().add(atb);
            dispose();
            }
        }
                    
        
        JOptionPane.showMessageDialog(this, message);
    }//GEN-LAST:event_btnBookTypeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBookType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jtfTypeID;
    private javax.swing.JTextField jtfTypeName;
    // End of variables declaration//GEN-END:variables
}
