/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package admin.ui;

import Operations.Checks;
import java.beans.PropertyVetoException;
import java.util.List;
import javax.swing.JOptionPane;
import model.dao.BookInfoDAO;
import model.dao.BookIssueDAO;
import model.dao.BookTypeDAO;
import model.dao.MemberInfoDAO;
import model.to.BookInfoTO;
import model.to.BookIssueTO;
import model.to.BookTypeTO;
import model.to.MemberInfoTO;

/**
 *
 * @author DELL
 */
public class AddBookIssue extends javax.swing.JInternalFrame {

    public AddBookIssue() {
        initComponents();
        jcbBookID.removeAllItems();
        jcbBookID.addItem("Choose A BookID");
        List<BookInfoTO> allbook = new BookInfoDAO().getAllRecord();
        if (allbook != null && allbook.size() > 0) {
            for (BookInfoTO bit : allbook) {
                jcbBookID.addItem(bit);
            }

        }
        jcbMemberID.removeAllItems();
        jcbMemberID.addItem("Choose A member ID");
        List<MemberInfoTO> allmember = new MemberInfoDAO().getAllRecord();
        if (allmember != null && allmember.size() > 0) {
            for (MemberInfoTO mit : allmember) {
                jcbMemberID.addItem(mit);
            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtfNoOfDays = new javax.swing.JTextField();
        dpBookDate = new admin.ui.DatePicker();
        btnAddBookIssue = new javax.swing.JButton();
        jcbMemberID = new javax.swing.JComboBox();
        jcbBookID = new javax.swing.JComboBox();

        setClosable(true);
        setMaximizable(true);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("MemberID:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("NoOfDays");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("BookID:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("BookDate");

        jtfNoOfDays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNoOfDaysActionPerformed(evt);
            }
        });

        btnAddBookIssue.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAddBookIssue.setText("Add Book Issue");
        btnAddBookIssue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBookIssueActionPerformed(evt);
            }
        });

        jcbMemberID.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbMemberID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbMemberIDActionPerformed(evt);
            }
        });

        jcbBookID.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbBookID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbBookIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(btnAddBookIssue, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtfNoOfDays, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcbMemberID, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jcbBookID, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(107, 107, 107))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                        .addComponent(dpBookDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 135, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btnAddBookIssue, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbMemberID, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbBookID, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfNoOfDays, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(dpBookDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(224, 224, 224))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfNoOfDaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNoOfDaysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNoOfDaysActionPerformed

    private void btnAddBookIssueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBookIssueActionPerformed
        String message = "";
        boolean allvalid = true;
        if (jcbMemberID.getSelectedIndex() == 0) {
            allvalid = false;
            message = "Please Choose  Any Value in Member ID";
        }
        if (jcbBookID.getSelectedIndex() == 0) {
            allvalid = false;
            message = "Please Choose  Any Value in Book ID";
        }
        String NoOfDays = jtfNoOfDays.getText();
        if (Checks.isEmpty(NoOfDays)) {
            allvalid = false;
            message = "Please fill Any Value in No Of Days";
        }
        if (dpBookDate.getSelectedDate() == null) {
            allvalid = false;
            message = "Please fill Any Value in Book Date";
        } //String Fine=jtfFine.getText();
        // if(Checks.isEmpty(Fine)){
        //allvalid=false;
        // message="Please fill Any Value in Fine";
        //}
        else if (Checks.isNumeric(NoOfDays)) {
            int nod = Integer.parseInt(NoOfDays);
            if (nod < 0) {
                message = "No Of days Can Not Be Negative";
            }
            //else if(Checks.isFloat(Fine)){
            //float fin=Float.parseFloat(Fine);
            // if(fin<0){
            // allvalid=false;
            //  message="Fine Can Not Be Negative";
        }
        if (allvalid) {
            BookInfoTO bit = (BookInfoTO) jcbBookID.getSelectedItem();
            MemberInfoTO mit = (MemberInfoTO) jcbMemberID.getSelectedItem();
             BookIssueTO data = new BookIssueTO();   
            data.setMemberID(mit.getMemberID());
            data.setBookID(bit.getBookID());
            data.setNoOfDays(Integer.parseInt(NoOfDays));
            data.setBookDate(dpBookDate.getSelectedDate());
            BookIssueDAO action = new BookIssueDAO();
            if (btnAddBookIssue.getText().contains("Add")) {
                if (action.insertRecord(data)) {
                    message = "new Book Issue Information Is Added To  System";
                } else {
                    message = action.getErrorMessage();

                }
            
            }

        }

    JOptionPane.showMessageDialog (this, message);
     
         
         
    }//GEN-LAST:event_btnAddBookIssueActionPerformed
    
    private void jcbMemberIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbMemberIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbMemberIDActionPerformed

    private void jcbBookIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbBookIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbBookIDActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddBookIssue;
    private admin.ui.DatePicker dpBookDate;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox jcbBookID;
    private javax.swing.JComboBox jcbMemberID;
    private javax.swing.JTextField jtfNoOfDays;
    // End of variables declaration//GEN-END:variables
}
