/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package admin.ui;

import Operations.Checks;
import javax.swing.JOptionPane;
import model.dao.LoginInfoDAO;
import model.to.LoginInfoTO;

/**
 *
 * @author DELL
 */
public class AddLoginInfo extends javax.swing.JInternalFrame {
   

    /**
     * Creates new form AddLoginInfo
     */
    public AddLoginInfo() {
        initComponents();
        jcbRoleName.removeAllItems();
        jcbRoleName.addItem("Choose any option");
        jcbRoleName.addItem("Admin");
        jcbRoleName.addItem("User");
    }
      public AddLoginInfo(LoginInfoTO lit) {
          this();
          if(lit!=null){
              jtfUserName.setText(lit.getUserName());
              jtfPassword.setText(lit.getPassword());
              jtfUserName.setText(lit.getRoleName());
              jtfUserName.setEditable(false);
              btnAddLogin.setText("Update Login Information");
              setTitle("Update Student Information");
          }
          
      }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtfPassword = new javax.swing.JTextField();
        jtfUserName = new javax.swing.JTextField();
        btnAddLogin = new javax.swing.JButton();
        jcbRoleName = new javax.swing.JComboBox();

        setClosable(true);
        setIconifiable(true);
        setTitle("Add Login Info");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Enter UserName :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText(" Enter Password:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText(" Enter RoleName:");

        jtfUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfUserNameActionPerformed(evt);
            }
        });

        btnAddLogin.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnAddLogin.setText("Add Login Information");
        btnAddLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddLoginActionPerformed(evt);
            }
        });

        jcbRoleName.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbRoleName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbRoleNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(182, 182, 182)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbRoleName, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(btnAddLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jcbRoleName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(btnAddLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddLoginActionPerformed
       
        String UserName=jtfUserName.getText();
        String Password=jtfPassword.getText();
       // String RoleName=jtfRoleName.getText();
        String message="";
        if(Checks.isEmpty(UserName)||Checks.isEmpty(Password)||jcbRoleName.getSelectedIndex()==0){
            message="Please Fill All The Boxes";
        }else{
            LoginInfoTO data=new LoginInfoTO();
            data.setUserName(UserName);
            data.setPassword(Password);
            data.setRoleName(jcbRoleName.getSelectedItem().toString());
            data.setLastLogin(null);
            LoginInfoDAO action=new LoginInfoDAO();
            if(btnAddLogin.getText().contains("Add")){
                
            
            if(action.insertRecord(data)){
                message="New Login Information Is added To The System";
            } else{
                message=action.getErrorMessage();
            }
            }else if(btnAddLogin.getText().contains("Update")){
              if(action.updateRecord(data)){
                message=" Login Information Is updated To The System";
            } else{
                message=action.getErrorMessage();
            } 
              ViewLoginInfo vli= new ViewLoginInfo();
              vli.setVisible(true);
              getDesktopPane().add(vli);
              dispose();
            }
                
            }
    

                
        
        JOptionPane.showMessageDialog(this, message);
    }//GEN-LAST:event_btnAddLoginActionPerformed

    private void jcbRoleNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbRoleNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbRoleNameActionPerformed

    private void jtfUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfUserNameActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox jcbRoleName;
    private javax.swing.JTextField jtfPassword;
    private javax.swing.JTextField jtfUserName;
    // End of variables declaration//GEN-END:variables
}
