package admin.ui;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
import admin.ui.AddLoginInfo;
import admin.ui.ViewLoginInfo;
import javax.swing.ImageIcon;
import javax.swing.JInternalFrame;
//import model.to.LoginInfoTO;

/**
 *
 * @author DELL
 */
public class AdminNewScreen extends javax.swing.JFrame {

    /**
     * Creates new form AdminNewScreen
     */
    public AdminNewScreen() {
        initComponents();
        setSize(1000, 860);
        setLocationRelativeTo(null);
        
        setIconImage(new ImageIcon(getClass().getResource("/admin/ui/gsraj.jpg")).getImage());
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmiAddLoginInfo = new javax.swing.JMenu();
        jmiViewLogin = new javax.swing.JMenuItem();
        jmiAddLogin = new javax.swing.JMenuItem();
        jmiAddMember = new javax.swing.JMenu();
        jmiViewMember = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        menuBookType = new javax.swing.JMenu();
        jmiAddBook = new javax.swing.JMenuItem();
        jmiViewBookType = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jmiViewBookInfo = new javax.swing.JMenuItem();
        jmiAddBookInfo = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jmiViewBookIssue = new javax.swing.JMenuItem();
        jmiAddBookIssue = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        desktopPane.setDesktopManager(null);
        desktopPane.setFocusCycleRoot(false);
        getContentPane().add(desktopPane, java.awt.BorderLayout.CENTER);

        jmiAddLoginInfo.setText("Login Info Operations");
        jmiAddLoginInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAddLoginInfoActionPerformed(evt);
            }
        });

        jmiViewLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/ui/s1.png"))); // NOI18N
        jmiViewLogin.setText("View Login Info");
        jmiViewLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiViewLoginActionPerformed(evt);
            }
        });
        jmiAddLoginInfo.add(jmiViewLogin);

        jmiAddLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/ui/add4.png"))); // NOI18N
        jmiAddLogin.setText("Add Login Info");
        jmiAddLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAddLoginActionPerformed(evt);
            }
        });
        jmiAddLoginInfo.add(jmiAddLogin);

        jMenuBar1.add(jmiAddLoginInfo);

        jmiAddMember.setText("Member Info");
        jmiAddMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAddMemberActionPerformed(evt);
            }
        });

        jmiViewMember.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/ui/s1.png"))); // NOI18N
        jmiViewMember.setText("View Member Info");
        jmiViewMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiViewMemberActionPerformed(evt);
            }
        });
        jmiAddMember.add(jmiViewMember);

        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/ui/add4.png"))); // NOI18N
        jMenuItem8.setText("Add Member Info");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiMemberInfo(evt);
            }
        });
        jmiAddMember.add(jMenuItem8);

        jMenuBar1.add(jmiAddMember);

        menuBookType.setText("Book Type Operations");

        jmiAddBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/ui/add1.png"))); // NOI18N
        jmiAddBook.setText("Add Book Type");
        jmiAddBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAddBookActionPerformed(evt);
            }
        });
        menuBookType.add(jmiAddBook);

        jmiViewBookType.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/ui/s5.png"))); // NOI18N
        jmiViewBookType.setText("View Book Type");
        jmiViewBookType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiViewBookTypeActionPerformed(evt);
            }
        });
        menuBookType.add(jmiViewBookType);

        jMenuBar1.add(menuBookType);

        jMenu4.setText("Book Info");

        jmiViewBookInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/ui/s5.png"))); // NOI18N
        jmiViewBookInfo.setText("View Book Info");
        jmiViewBookInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiViewBookInfoActionPerformed(evt);
            }
        });
        jMenu4.add(jmiViewBookInfo);

        jmiAddBookInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/ui/add4.png"))); // NOI18N
        jmiAddBookInfo.setText("Add Book Info");
        jmiAddBookInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAddBookInfoActionPerformed(evt);
            }
        });
        jMenu4.add(jmiAddBookInfo);

        jMenuBar1.add(jMenu4);

        jMenu7.setText("Book Issue");

        jmiViewBookIssue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/ui/s2.png"))); // NOI18N
        jmiViewBookIssue.setText("View Book Issue");
        jmiViewBookIssue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiViewBookIssueActionPerformed(evt);
            }
        });
        jMenu7.add(jmiViewBookIssue);

        jmiAddBookIssue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/ui/add3.png"))); // NOI18N
        jmiAddBookIssue.setText("Add Book Issue");
        jmiAddBookIssue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAddBookIssueActionPerformed(evt);
            }
        });
        jMenu7.add(jmiAddBookIssue);

        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiAddMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAddMemberActionPerformed
        AddMemberInfo ami = new AddMemberInfo();
        ami.setVisible(true);
        desktopPane.add(ami);
    }//GEN-LAST:event_jmiAddMemberActionPerformed

    private void jmiViewLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiViewLoginActionPerformed
        ViewLoginInfo vli = new ViewLoginInfo();
        vli.setVisible(true);
        desktopPane.add(vli);
    }//GEN-LAST:event_jmiViewLoginActionPerformed

    private void jmiAddBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAddBookActionPerformed
       AddBookType abt= new AddBookType();
       abt.setVisible(true);
       desktopPane.add(abt);
    }//GEN-LAST:event_jmiAddBookActionPerformed

    private void jmiViewBookTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiViewBookTypeActionPerformed
        ViewBookType vbt = new ViewBookType();
        vbt.setVisible(true);
        desktopPane.add(vbt);
    }//GEN-LAST:event_jmiViewBookTypeActionPerformed

    private void jmiAddBookInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAddBookInfoActionPerformed
       AddBookInfo abi= new AddBookInfo();
       abi.setVisible(true);
       desktopPane.add(abi); 
    }//GEN-LAST:event_jmiAddBookInfoActionPerformed

    private void jmiMemberInfo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiMemberInfo
        AddMemberInfo ami = new AddMemberInfo();
        ami.setVisible(true);
        desktopPane.add(ami);
    }//GEN-LAST:event_jmiMemberInfo

    private void jmiViewMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiViewMemberActionPerformed
       ViewMemberInfo vmi = new ViewMemberInfo();
        vmi.setVisible(true);
        desktopPane.add(vmi);
    }//GEN-LAST:event_jmiViewMemberActionPerformed

    private void jmiAddBookIssueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAddBookIssueActionPerformed
        AddBookIssue abii= new AddBookIssue();
       abii.setVisible(true);
       desktopPane.add(abii); 
    }//GEN-LAST:event_jmiAddBookIssueActionPerformed

    private void jmiAddLoginInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAddLoginInfoActionPerformed
          AddLoginInfo ali = new AddLoginInfo();
        ali.setVisible(true);
        desktopPane.add(ali);
    }//GEN-LAST:event_jmiAddLoginInfoActionPerformed

    private void jmiAddLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAddLoginActionPerformed
        showFrame(new AddLoginInfo());
    }//GEN-LAST:event_jmiAddLoginActionPerformed

    private void jmiViewBookIssueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiViewBookIssueActionPerformed
       ViewBookIssue vbi = new ViewBookIssue();
        vbi.setVisible(true);
        desktopPane.add(vbi);
    }//GEN-LAST:event_jmiViewBookIssueActionPerformed

    private void jmiViewBookInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiViewBookInfoActionPerformed
         ViewBookInfo vbin = new ViewBookInfo();
        vbin.setVisible(true);
        desktopPane.add(vbin);
    }//GEN-LAST:event_jmiViewBookInfoActionPerformed

    
    private void showFrame(JInternalFrame jif){
        jif.setVisible(true);
        desktopPane.add(jif);
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminNewScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminNewScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminNewScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminNewScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminNewScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jmiAddBook;
    private javax.swing.JMenuItem jmiAddBookInfo;
    private javax.swing.JMenuItem jmiAddBookIssue;
    private javax.swing.JMenuItem jmiAddLogin;
    private javax.swing.JMenu jmiAddLoginInfo;
    private javax.swing.JMenu jmiAddMember;
    private javax.swing.JMenuItem jmiViewBookInfo;
    private javax.swing.JMenuItem jmiViewBookIssue;
    private javax.swing.JMenuItem jmiViewBookType;
    private javax.swing.JMenuItem jmiViewLogin;
    private javax.swing.JMenuItem jmiViewMember;
    private javax.swing.JMenu menuBookType;
    // End of variables declaration//GEN-END:variables
}
