/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package admin.ui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import model.dao.LoginInfoDAO;
import model.to.LoginInfoTO;

/**
 *
 * @author DELL
 */
public class ViewLoginInfo extends javax.swing.JInternalFrame {

    List<LoginInfoTO> alllogin;
    JPopupMenu popupmenu;
    int row;

    public ViewLoginInfo() {
        initComponents();
        bindLoginInfo();
        row = -1;
        popupmenu = new JPopupMenu();
        JMenuItem jmiDelete = new JMenuItem("Delete This Record");
        JMenuItem jmiEdit = new JMenuItem("Edit This Record");
        popupmenu.add(jmiDelete);
        popupmenu.add(jmiEdit);
        jmiDelete.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                deleteRecord();
            }
        });
        jmiEdit.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                editRecord();
            }
        });
    }

    private void editRecord() {
        if (row != -1 && alllogin != null && alllogin.size() > 0) {
            LoginInfoTO lit = alllogin.get(row);
            if (lit != null) {
                AddLoginInfo ali = new AddLoginInfo(lit);
                ali.setVisible(true);
                getDesktopPane().add(ali);
                dispose();
            }
        }
    }

    private void deleteRecord() {
        if (row != -1 && alllogin != null && alllogin.size() > 0) {
            int Selection = JOptionPane.showConfirmDialog(this, "Are You Sure To Delete This Record ?", "Message From System", JOptionPane.YES_NO_OPTION);
            if (Selection == JOptionPane.YES_OPTION) {
                LoginInfoTO lit = alllogin.get(row);
                if (lit != null) {
                    LoginInfoDAO action = new LoginInfoDAO();
                    String message = "";
                    if (action.deleteRecord(lit.getUserName())) {
                        message = "Record Is Deleted From The System";
                    } else {
                        message = action.getErrorMessage();
                    }
                    JOptionPane.showMessageDialog(this, message);
                    row = -1;
                    bindLoginInfo();

                }
            }

        }


    }

    private void bindLoginInfo() {
        alllogin = new LoginInfoDAO().getAllRecord();
        String[] columnNames = {"UserName", "Password", "RoleName"};
        Object[][] data = null;

        if (alllogin != null && alllogin.size() > 0) {
            data = new Object[alllogin.size()][columnNames.length];
            int i = 0;
            for (LoginInfoTO lit : alllogin) {
                data[i] = new Object[]{lit.getUserName(), lit.getPassword(), lit.getRoleName()};
                i++;
            }

        } else {
            data = new Object[1][columnNames.length];
            data[0] = new Object[]{"There Is no Record", "There is No Record", "There is No Record"};

        }
        DefaultTableModel dtm = new DefaultTableModel(data, columnNames) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        tableLoginInfo.setModel(dtm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableLoginInfo = new javax.swing.JTable();
        btnRefresh = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("View Login Info");

        tableLoginInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableLoginInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableLoginInfoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableLoginInfo);

        btnRefresh.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/ui/r1.png"))); // NOI18N
        btnRefresh.setText("Refresh Table");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableLoginInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableLoginInfoMouseClicked
        //if(evt.getButton()==MouseEvent.BUTTON3){
        if (SwingUtilities.isRightMouseButton(evt)) {
            // JoptionPane.showMessageDialog(this,"Right Click");
            int rowpos = tableLoginInfo.rowAtPoint(evt.getPoint());
            tableLoginInfo.getSelectionModel().setSelectionInterval(rowpos, rowpos);
            popupmenu.show(tableLoginInfo, evt.getX(), evt.getY());
            // System.out.Println("tableLoginInfo.getSelectedRow()");
            row = tableLoginInfo.getSelectedRow();
        }
    }//GEN-LAST:event_tableLoginInfoMouseClicked

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        bindLoginInfo();
    }//GEN-LAST:event_btnRefreshActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefresh;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableLoginInfo;
    // End of variables declaration//GEN-END:variables
}
