/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package admin.ui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import model.dao.LoginInfoDAO;
import model.dao.MemberInfoDAO;
import model.to.LoginInfoTO;
import model.to.MemberInfoTO;

/**
 *
 * @author DELL
 */
public class ViewMemberInfo extends javax.swing.JInternalFrame {

    List<MemberInfoTO> allmember;
    JPopupMenu popupmenu;
    int row;

    public ViewMemberInfo() {
        initComponents();
        bindMemberInfo();
        row = -1;
        popupmenu = new JPopupMenu();
        JMenuItem jmiDelete = new JMenuItem("Delete This Record");
        JMenuItem jmiEdit = new JMenuItem("Edit This Record");
        popupmenu.add(jmiDelete);
        popupmenu.add(jmiEdit);
        jmiDelete.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                deleteRecord();
            }
        });
          jmiEdit.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                editRecord();
            }
        });
    }
    private void editRecord(){
      if (row != -1 && allmember != null && allmember.size() > 0) { 
           MemberInfoTO mit = allmember.get(row);
                if (mit != null) {
                    AddMemberInfo ami=new AddMemberInfo(mit);
                    ami.setVisible(true);
                    getDesktopPane().add(ami);
                    dispose();
                }
      }  
    }
    private void deleteRecord() {
        if (row != -1 && allmember != null && allmember.size() > 0) {
            int Selection = JOptionPane.showConfirmDialog(this, "Are You Sure To Delete This Record ?", "Message From System", JOptionPane.YES_NO_OPTION);
            if (Selection == JOptionPane.YES_OPTION) {
                MemberInfoTO mit = allmember.get(row);
                if (mit != null) {
                    MemberInfoDAO action = new MemberInfoDAO();
                    String message = "";
                    if (action.deleteRecord(mit.getMemberID())){
                        message = "Record Is Deleted From The System";
                    } else {
                        message = action.getErrorMessage();
                    }
                    JOptionPane.showMessageDialog(this, message);
                    row = -1;
                    bindMemberInfo();


                }}

            }


        }
    

    private void bindMemberInfo() {
        allmember = new MemberInfoDAO().getAllRecord();
        String[] columnNames = {"Member ID", "Member Name", "Address", "DOB", "Contact NO", "Fee", "Start Date"};
        Object[][] data = null;

        if (allmember != null && allmember.size() > 0) {
            data = new Object[allmember.size()][columnNames.length];
            int i = 0;
            for (MemberInfoTO mit : allmember) {
                data[i] = new Object[]{mit.getMemberID(), mit.getMemberName(), mit.getAddress(), mit.getDOB(), mit.getContactNo(), mit.getFee(), mit.getStartDate()};
                i++;
            }

        } else {
            data = new Object[1][columnNames.length];
            data[0] = new Object[]{"There Is no Record", "There is No Record", "There is No Record", "There is No Record", "There is No Record", "There is No Record", "There is No Record"};

        }
        DefaultTableModel dtm = new DefaultTableModel(data, columnNames) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        tableMemberInfo.setModel(dtm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableMemberInfo = new javax.swing.JTable();
        btnRefresh = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("View Member Info");

        tableMemberInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableMemberInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMemberInfoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableMemberInfo);

        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/ui/r3.png"))); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(121, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
            .addGroup(layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableMemberInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMemberInfoMouseClicked
        //if(evt.getButton()==MouseEvent.BUTTON3){
        if (SwingUtilities.isRightMouseButton(evt)) {
            // JoptionPane.showMessageDialog(this,"Right Click");
            int rowpos = tableMemberInfo.rowAtPoint(evt.getPoint());
            tableMemberInfo.getSelectionModel().setSelectionInterval(rowpos, rowpos);
            popupmenu.show(tableMemberInfo, evt.getX(), evt.getY());
            // System.out.Println("tableLoginInfo.getSelectedRow()");
            row = tableMemberInfo.getSelectedRow();
        }
    }//GEN-LAST:event_tableMemberInfoMouseClicked

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        bindMemberInfo();
    }//GEN-LAST:event_btnRefreshActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefresh;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableMemberInfo;
    // End of variables declaration//GEN-END:variables
}
